language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo add-apt-repository -y ppa:tuleu/precise-backports
  - sudo apt-get -y update
  - sudo apt-get install libopencv-dev libgflags-dev libgoogle-glog-dev libeigen3-dev

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
