language: cpp

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq python-dev python-numpy libeigen3-dev libgflags-dev libgoogle-glog

before_script:
  - pwd && ls
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.12
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make -j8 install
  - cd ..
  - mkdir build
  - cd build
  - cmake ..

script: make
