language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

branches:
  only:
    - master

notifications:
  email: false

before_install:
  # Make sure travis has the ability to commit/push to the repository. This is
  # needed to publish documentation after the build is finished.
  - openssl aes-256-cbc -K $encrypted_6a2f0cd4845b_key -iv $encrypted_6a2f0cd4845b_iv -in travisci_rsa.enc -out documentation/travisci_rsa -d
  - chmod 0600 documentation/travisci_rsa
  - cp config/travisci_rsa ~/.ssh/id_rsa

install:
  - echo $TRAVIS_OS_NAME

  # Linux: Get Doxygen, glog, eigen, and gflags, and update g++/gcc to 4.8.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:tuleu/precise-backports; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get update -qq; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install --yes build-essential doxygen libgflags-dev libgoogle-glog-dev libeigen3-dev; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python-software-properties; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install gcc-4.8 g++-4.8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config gcc; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --config g++; fi

before_script:
  # Linux: Download OpenCV.
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export CXX="g++-4.8"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git clone https://github.com/Itseez/opencv.git; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd opencv; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then git checkout 2.4; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then mkdir build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd build; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cmake -DBUILD_opencv_features2d=ON -DBUILD_opencv_highgui=ON
    -DBUILD_opencv_imgproc=ON -DBUILD_opencv_core=ON -DBUILD_opencv_nonfree=ON -DBUILD_opencv_calib3d=ON
    -DBUILD_opencv_video=OFF -DBUILD_opencv_objdetect=OFF -DBUILD_opencv_ml=OFF -DBUILD_opencv_flann=ON
    -DBUILD_opencv_gpu=OFF -DBUILD_opencv_photo=OFF -DBUILD_opencv_stitching=OFF -DBUILD_opencv_contrib=OFF
    -DBUILD_opencv_legacy=ON -DBUILD_opencv_ocl=OFF -DBUILD_opencv_superres=OFF -DBUILD_opencv_viz=OFF ..; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make -j8; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo make -j8 install; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then cd ../..; fi

  # Generate a makefile for berkeley_sfm.
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script:
  - make
  - cd ../bin/
  - ./run_tests --gtest_list_tests
  - ./run_tests
  - cd ..

after_success:
  # Publish documentation. Only publish from one of the build jobs.
  - if [ "$CXX" == "g++-4.8" ]; then ./documentation/publish_documentation.sh; fi
