language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo add-apt-repository -y ppa:tuleu/precise-backports
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install build-essential libgflags-dev libgoogle-glog-dev libeigen3-dev
  - sudo apt-get install python-software-properties
  - sudo apt-get install gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 20
  - sudo update-alternatives --config gcc
  - sudo update-alternatives --config g++

before_script:
  - export CXX="g++-4.8"
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - git checkout 2.4.12
  - mkdir build
  - cd build
  - cmake ..
  - make -j8
  - sudo make -j8 install
  - cd ../..
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make
